# Generated by Django 3.1.7 on 2021-04-05 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bids_listing_comments_listings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bids',
            new_name='Bid',
        ),
        migrations.RenameModel(
            old_name='Listings',
            new_name='Listing',
        ),
        migrations.RenameModel(
            old_name='Listing_Comments',
            new_name='Listing_Comment',
        ),
    ]
