# Generated by Django 3.1.7 on 2021-04-05 03:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20210404_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='close_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 11, 20, 33, 32, 185390)),
        ),
    ]
