# Generated by Django 3.1.7 on 2021-04-05 19:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_listing_close_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='listing_cat',
            field=models.CharField(choices=[('FSH', 'Fashion'), ('TOY', 'Toys'), ('ELC', 'Electronics'), ('HOM', 'Home'), ('ART', 'Art'), ('LIT', 'Literature')], default='HOM', max_length=20),
        ),
        migrations.AlterField(
            model_name='listing',
            name='close_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 12, 12, 13, 37, 589133)),
        ),
    ]
